// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBByO9UkFcMAttDGxPDp07SOfSWCRrXrxM',
    appId: '1:919323518278:android:8dd8cc82dccc5979ce7147',
    messagingSenderId: '919323518278',
    projectId: 'assignmentproject-6e9a5',
    storageBucket: 'assignmentproject-6e9a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY84LRDvU4fj-wmNLkt8qiUUtg3yrcNDg',
    appId: '1:919323518278:ios:322d1afcedc3dfd2ce7147',
    messagingSenderId: '919323518278',
    projectId: 'assignmentproject-6e9a5',
    storageBucket: 'assignmentproject-6e9a5.appspot.com',
    iosClientId: '919323518278-bv9ttdcm7i0tpqbgfr9e8vbsjp3lscri.apps.googleusercontent.com',
    iosBundleId: 'com.example.tictokClone2',
  );
}
